# Topic 3.2 - 表拼接

## 1. 表拼接的概念

表拼接要比表连接简单许多，它的概念就是将两个表按照行的方向拼接在一起，得到一个新的表：

- 比方说，我们有两个表，它们的列完全一致，行数不一致没有关系：

<div align="center">
    <img src="./图1.png" width="600">
</div>

- 通过表拼接，我们将这两个表按照行的方向拼接在一起，得到一个新的表：

<div align="center">
    <img src="./图2.png" width="300">
</div>

## 2. SQL 中的表拼接

在 SQL 中，表拼接的操作使用 `UNION ALL` 关键字来实现：

```sql
SELECT column1, column2, ...
FROM table1
...

UNION ALL

SELECT column1, column2, ...
FROM table2
...
```

这个语法方式有些特殊，同学们之前可能没有见过，下面我们来逐步分析一下：

- 这段 SQL 语句由两段 `SELECT` 语句组成，每段 `SELECT` 语句都产生一个小表
- 按照我们上面的例子，第一段 `SELECT` 语句产生了张三李四那个学生表，第二段 `SELECT` 语句产生了 Alice Bob 那个学生表
- 这两段 `SELECT` 语句之间使用了 `UNION ALL` 关键字，这个关键字的作用就是将两段 `SELECT` 语句产生的小表按照行的方向拼接在一起，得到一个新的表
- 需要注意的是，使用 `UNION ALL` 进行表拼接时，要求两段 `SELECT` 语句产生的小表的**列数、列名、列的数据类型**必须一致，否则会报错
- 除此之外，每段 `SELECT` 语句中还可以包含一些其他的 SQL 语句，比如 `WHERE`、`GROUP BY`、`ORDER BY` 等等，这些 SQL 语句会在每段 `SELECT` 语句中独立执行，不会相互影响，只要保证每段 `SELECT` 语句产生的小表的列数、列名、列的数据类型一致就可以了

除了 `UNION ALL` 以外，还有一个 `UNION` 关键字也可以用来进行表拼接，但是它和 `UNION ALL` 的区别在于：

- `UNION` 会在拼接完成后自动去重，也就是说，如果两段 `SELECT` 语句产生的小表中有重复的行，那么在使用 `UNION` 进行表拼接时，这些重复的行只会保留一行，其他的重复行会被丢弃掉
- `UNION ALL` 则不会去重，所有的行都会被保留，所以在使用 `UNION ALL` 进行表拼接时，如果两段 `SELECT` 语句产生的小表中有重复的行，那么在拼接完成后，这些重复的行都会被保留

我们在 Chinook 数据库中，使用 `UNION ALL` 和 `UNION` 来做一些练习：

- 查询 `InvoiceLine` 表中曾经被卖出过的 `TrackId`，以及 `Track` 表中 `Milliseconds` 大于 300000 的 `TrackId`，并将这两部分的结果拼接在一起，并且去重：

In [2]:
%%sql
SELECT DISTINCT
    TrackId
FROM InvoiceLine

UNION

SELECT DISTINCT
    TrackId
FROM Track
WHERE Milliseconds > 300000

      TrackId
0           1
1           2
2           3
3           4
4           5
...       ...
2439     3494
2440     3496
2441     3498
2442     3499
2443     3500

[2444 rows x 1 columns]

- 将 `Customer` 表中的 `FirstName` 和 `LastName` 列拼接成一个新的列 `FullName`，同样，在 `Employee` 表中也将 `FirstName` 和 `LastName` 列拼接成一个新的列 `FullName`，然后将这两部分的结果拼接在一起，将客户和员工的电话和 Email 信息都展示出来：

In [4]:
%%sql
SELECT
    CONCAT(FirstName, ' ', LastName) AS FullName,
    Phone,
    Email
FROM Customer

UNION ALL

SELECT
    CONCAT(FirstName, ' ', LastName) AS FullName,
    Phone,
    Email
FROM Employee

                 FullName               Phone                     Email
0          Luís Gonçalves  +55 (12) 3923-5555      luisg@embraer.com.br
1           Leonie Köhler    +49 0711 2842222     leonekohler@surfeu.de
2       François Tremblay   +1 (514) 721-4711       ftremblay@gmail.com
3            Bjørn Hansen     +47 22 44 22 22     bjorn.hansen@yahoo.no
4   František Wichterlová    +420 2 4172 5555  frantisekw@jetbrains.com
..                    ...                 ...                       ...
62          Margaret Park   +1 (403) 263-4423  margaret@chinookcorp.com
63          Steve Johnson    1 (780) 836-9987     steve@chinookcorp.com
64       Michael Mitchell   +1 (403) 246-9887   michael@chinookcorp.com
65            Robert King   +1 (403) 456-9986    robert@chinookcorp.com
66         Laura Callahan   +1 (403) 467-3351     laura@chinookcorp.com

[67 rows x 3 columns]