# Topic 2.2 - Pandas 中的数据创建与存储

本节开始之前，我们先导入 pandas 库：

In [110]:
import pandas as pd

## 1. 数据的创建

### (1) 自创 DataFrame 数据

在上一节，我们介绍了可以使用 Python 自带的数据结构（如列表、字典等）来创建 DataFrame 数据：

- 一种是列表套列表的形式，需要指定列名：

In [111]:
data_df_1 = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ],
    columns=['A', 'B', 'C']
)
data_df_1

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

- 另一种是字典套列表的形式，使用键作为列名：

In [112]:
data_df_2 = pd.DataFrame({
    'A': [1, 4, 7],
    'B': [2, 5, 8],
    'C': [3, 6, 9]
})
data_df_2

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

在创建好数据之后，也可以插入新列和新行：

- 插入新列可以直接通过列名赋值一个列表的方式实现：

In [113]:
data_df_2["D"] = [10, 11, 12]
data_df_2

   A  B  C   D
0  1  2  3  10
1  4  5  6  11
2  7  8  9  12

- 插入新行有两种方法，一种是使用 `loc` 方法，指定新行的行名，然后赋值一个列表：

In [114]:
data_df_2.loc[3] = [13, 14, 15, 16]
data_df_2

    A   B   C   D
0   1   2   3  10
1   4   5   6  11
2   7   8   9  12
3  13  14  15  16

- 插入新行的另一种方法是使用 `concat` 方法，这种方法比较复杂，需要传入一个新的 DataFrame，然后通过 `ignore_index=True` 参数来重置索引：

In [115]:
data_df_2 = pd.concat([data_df_2, pd.DataFrame({'A': [17], 'B': [18], 'C': [19], 'D': [20]})], ignore_index=True)
data_df_2

    A   B   C   D
0   1   2   3  10
1   4   5   6  11
2   7   8   9  12
3  13  14  15  16
4  17  18  19  20

### (2) 从文件中读取数据

Pandas 支持从多种文件格式中读取数据，包括 CSV、Excel、JSON 等。

从 CSV 文件读取数据可以使用 `pd.read_csv()` 函数，当中要强调文件路径：

In [116]:
df_students = pd.read_csv('../data/students.csv')
df_students

             name  class  gender  age  chinese  math  english
0   Alice Johnson      1  Female   18       85    88       90
1       Bob Smith      2    Male   19       78    75       80
2   Charlie Brown      3    Male   18       92    90       94
3    David Miller      1    Male   20       88    85       87
4     Emma Wilson      2  Female   19       76    78       74
..            ...    ...     ...  ...      ...   ...      ...
86   Jonah Larson      3    Male   21       78    76       77
87   Kylie Newman      1  Female   18       85    83       84
88   Lucas Porter      2    Male   22       91    92       93
89   Megan Arnold      3  Female   19       79    77       78
90    Nick Keller      1    Male   20       87    85       88

[91 rows x 7 columns]

从 Excel 文件读取数据可以使用 `pd.read_excel()` 函数，同样需要指定文件路径，并且还需要指定工作表名称（如果有多个工作表的话）：

In [117]:
df_sales = pd.read_excel('../data/sales.xlsx', sheet_name='sales')
df_sales

           date   product  price  quantity
0    2024-01-01    Camera   4599         6
1    2024-01-01   Monitor   1599         5
2    2024-01-01    Tablet   2999        11
3    2024-01-01     Phone   4999         4
4    2024-01-01    Laptop   6999        10
..          ...       ...    ...       ...
328  2024-02-29   Speaker    899        11
329  2024-02-29  Keyboard    399        11
330  2024-02-29    Laptop   6999        10
331  2024-02-29  Keyboard    399        14
332  2024-02-29    Laptop   6999        14

[333 rows x 4 columns]

从 JSON 文件读取数据可以使用 `pd.read_json()` 函数，指定文件路径即可：

In [118]:
df_records = pd.read_json('../data/records.json')
df_records

   id       date category  value   status
0   1 2024-01-01        A   12.5       ok
1   2 2024-01-01        B    9.8       ok
2   3 2024-01-02        A   15.2  warning
3   4 2024-01-02        C    7.1       ok
4   5 2024-01-03        B   11.4    error

## 2. 数据的存储

Pandas 也支持将 DataFrame 数据存储为多种文件格式，包括 CSV、Excel、JSON 等。

- 将数据存储为 CSV 文件可以使用 `to_csv()` 方法，指定文件路径即可

    - 这当中可以通过 `index=False` 参数来避免存储行索引
    - 如果设置 `index=True`，则会将行索引，也就是行号存储到文件中

In [119]:
data_people_info = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Melbourne", "Sydney", "Brisbane"]
})

data_people_info

      name  age       city
0    Alice   25  Melbourne
1      Bob   30     Sydney
2  Charlie   35   Brisbane

In [120]:
data_people_info.to_csv('../data/people_info.csv', index=False)

- 将数据存储为 Excel 文件可以使用 `to_excel()` 方法，指定文件路径和工作表名称即可：

In [121]:
data_people_info.to_excel('../data/people_info.xlsx', sheet_name='info', index=False)

- 将数据存储为 JSON 文件可以使用 `to_json()` 方法，指定文件路径即可

    - 这当中可以通过 `orient` 参数来指定 JSON 的格式，如果设置为 `records`，则**每行**数据会被存储为一个 JSON 对象，如果设置为 `columns`，则**每列**数据会被存储为一个 JSON 对象
    - 还可以通过 `lines` 参数来指定是否将每个 JSON 对象存储在单独的一行，如果设置为 `True`，则每个 JSON 对象会被存储在单独的一行
    - 另外，还可以通过 `indent` 参数来指定缩进的空格数，以便于阅读

In [122]:
data_people_info.to_json('../data/people_info.json', orient='records', lines=False, indent=4)